{% set name = "pyppdf" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: beb94e8ce9e8893f5dc17d4b73176019b7e88d8f3e38eb72782a3a6c0bebffeb

build:
  noarch: python
  number: 1
  entry_points:
    - pyppdf = pyppdf.pyppeteer_pdf:cli
    - pyppdf-install = pyppdf.install:install
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - certifi
    - click
    - psutil
    - litereval >=0.0.9
    - pyppeteer >=0.2.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyppdf
    - pyppdf.patch_pyppeteer
  commands:
    - pyppdf --help
    - pyppdf-install

about:
  home: https://github.com/kiwi0fruit/pyppdf
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Pyppeteer PDF. Print html sites and files to pdf via pyppeteer (uses patched pyppeteer that by default downloads updated Chromium revision via https with certifi)."
  doc_url: https://github.com/kiwi0fruit/pyppdf
  dev_url: https://github.com/kiwi0fruit/pyppdf

extra:
  recipe-maintainers:
    - kiwi0fruit
